namespace CWTools.Games

open System
open System.Collections.Concurrent
open CWTools.Common
open CWTools.Validation
open CWTools.Validation.ValidationCore
open CWTools.Utilities.Utils
open CWTools.Rules
open CWTools.Process
open CWTools.Parser.Types
open CWTools.Validation.Stellaris.STLLocalisationValidation
open CWTools.Utilities.Position
open CWTools.Process.Scopes
open FSharp.Collections.ParallelSeq
open CWTools.Process.Localisation

type LookupFileValidator<'T when 'T :> ComputedData> =
    Files.FileManager -> RuleValidationService option -> Lookup -> FileValidator<'T>

type ValidationManagerSettings<'T when 'T :> ComputedData> =
    { validators: (StructureValidator<'T> * string) list
      experimentalValidators: (StructureValidator<'T> * string) list
      heavyExperimentalValidators: (LookupValidator<'T> * string) list
      experimental: bool
      fileValidators: (FileValidator<'T> * string) list
      lookupValidators: (LookupValidator<'T> * string) list
      lookupFileValidators: (LookupFileValidator<'T> * string) list
      useRules: bool
      debugRulesOnly: bool
      localisationValidators: LocalisationValidator<'T> list }

type ValidationManagerServices<'T when 'T :> ComputedData> =
    { resources: IResourceAPI<'T>
      lookup: Lookup
      ruleValidationService: RuleValidationService option
      infoService: InfoService option
      localisationKeys: unit -> (Lang * Set<string>) array
      fileManager: Files.FileManager }

open System.Collections.Generic

type ErrorCache() =

    let sourceToErrorsForTargets =
        ConcurrentDictionary<string, ConcurrentDictionary<string, CWError list>>()

    let targetToErrors = ConcurrentDictionary<string, HashSet<CWError>>()
    let selfErrors = ConcurrentDictionary<string, HashSet<CWError>>()

    let monitor = new Object()
    
    /// 清理不存在文件的缓存条目，防止内存泄漏
    member this.Cleanup(existingFiles: Set<string>) =
        lock monitor (fun () ->
            // 清理 sourceToErrorsForTargets 中不存在的文件
            let sourceFiles = sourceToErrorsForTargets.Keys |> Seq.toList
            for sourceFile in sourceFiles do
                if not (existingFiles.Contains sourceFile) then
                    match sourceToErrorsForTargets.TryRemove sourceFile with
                    | true, _ -> ()
                    | _ -> ()
            
            // 清理 targetToErrors 中不存在的文件
            let targetFiles = targetToErrors.Keys |> Seq.toList
            for targetFile in targetFiles do
                if not (existingFiles.Contains targetFile) then
                    match targetToErrors.TryRemove targetFile with
                    | true, _ -> ()
                    | _ -> ()
            
            // 清理 selfErrors 中不存在的文件
            let selfErrorFiles = selfErrors.Keys |> Seq.toList
            for selfFile in selfErrorFiles do
                if not (existingFiles.Contains selfFile) then
                    match selfErrors.TryRemove selfFile with
                    | true, _ -> ()
                    | _ -> ()
        )

    member this.AddErrorsGeneratedByFile(fromEntity: Entity, errorsForFiles: CWError seq) =
        lock monitor (fun () ->
            let errorsForFiles = errorsForFiles |> Seq.toList
            let wrappedInlineErrors =
                errorsForFiles
                |> List.filter (fun error -> error.code = "CW274")
                |> List.collect (fun error -> error.relatedErrors |> Option.defaultValue [])

            let isWrappedInlineError (error: CWError) =
                wrappedInlineErrors
                |> List.exists (fun related ->
                    related.message = error.message
                    && related.location.FileName = error.range.FileName
                    && related.location.StartLine = error.range.StartLine
                    && related.location.StartColumn = error.range.StartColumn
                    && related.location.EndLine = error.range.EndLine
                    && related.location.EndColumn = error.range.EndColumn)

            let errorsForFiles =
                errorsForFiles
                |> List.filter (fun error -> error.code = "CW274" || not (isWrappedInlineError error))

            let mutable impactedFiles = HashSet<string>()
            // Remove existing errors generated by this file
            if sourceToErrorsForTargets.ContainsKey fromEntity.filepath then
                match sourceToErrorsForTargets.TryRemove fromEntity.filepath with
                | true, oldErrors ->
                    for pair in oldErrors do
                        let targetFile, errors = pair.Key, pair.Value
                        impactedFiles.Add targetFile |> ignore
                        // 安全地访问 targetToErrors，确保键存在
                        match targetToErrors.TryGetValue targetFile with
                        | true, bag ->
                            for error in errors do
                                bag.Remove error |> ignore
                        | false, _ -> () // 键不存在，跳过
                | _ -> ()

            match selfErrors.TryRemove fromEntity.filepath with
            | true, _ -> impactedFiles.Add fromEntity.filepath |> ignore
            | _ -> ()

            // Add new errors
            let groupedErrors = errorsForFiles |> Seq.groupBy (fun x -> x.range.FileName)
            let newErrors = new ConcurrentDictionary<string, CWError list>()
            sourceToErrorsForTargets.[fromEntity.filepath] <- newErrors

            for targetFile, cwErrors in groupedErrors do
                if fromEntity.filepath = targetFile then
                    // 使用 TryAdd 或索引器安全地更新字典
                    let _ = selfErrors.TryGetValue(targetFile)
                    selfErrors.[targetFile] <- new HashSet<CWError>(cwErrors)
                else
                    impactedFiles.Add targetFile |> ignore
                    newErrors.[targetFile] <- cwErrors |> List.ofSeq
                    let bag = targetToErrors.GetOrAdd(targetFile, (fun _ -> new HashSet<CWError>()))

                    for error in cwErrors do
                        bag.Add error |> ignore

            impactedFiles)

    member this.GetErrorsForEntity(entity: Entity) = this.GetErrorsForFile entity.filepath

    member this.GetErrorsForFile(filepath: string) =
        match targetToErrors.TryGetValue(filepath), selfErrors.TryGetValue(filepath) with
        | (true, errors1), (true, errors2) -> Some(Seq.append errors1 errors2 |> Seq.toList)
        | (false, _), (true, errors)
        | (true, errors), (false, _) -> Some(Seq.toList errors)
        | _ -> None

    member this.GetNonSelfErrorsForFile(entity: Entity) =
        match targetToErrors.TryGetValue(entity.filepath) with
        | true, cwErrors -> Some(Seq.toList cwErrors)
        | _ -> None

type ValidationManager<'T when 'T :> ComputedData>
    (
        settings: ValidationManagerSettings<'T>,
        services: ValidationManagerServices<'T>,
        validateLocalisationCommand,
        defaultContext: ScopeContext,
        noneContext: ScopeContext,
        errorCache: ErrorCache
    ) =
    let resources = services.resources
    let validators = settings.validators
    let errorCache = errorCache
    let cancellationCheck = System.Threading.AsyncLocal<unit -> bool>()

    // A DidChange interactive pass and the following save often validate the exact
    // same immutable Entity with the exact same RuleValidationService. Keep a small
    // bounded LRU of completed results so save-time deep validation can reuse them
    // without retaining results for an unbounded number of edited workspace files.
    let maxDetachedRuleResults = 32
    let detachedRuleResults =
        Dictionary<string, struct (Entity * RuleValidationService * ValidationResult)>()
    let detachedRuleResultOrder = LinkedList<string>()
    let detachedRuleResultNodes = Dictionary<string, LinkedListNode<string>>()
    let detachedRuleResultGate = obj ()

    let removeDetachedRuleResultUnsafe filepath =
        detachedRuleResults.Remove filepath |> ignore
        match detachedRuleResultNodes.TryGetValue filepath with
        | true, node ->
            detachedRuleResultOrder.Remove node
            detachedRuleResultNodes.Remove filepath |> ignore
        | _ -> ()

    let removeDetachedRuleResult filepath =
        lock detachedRuleResultGate (fun () -> removeDetachedRuleResultUnsafe filepath)

    let storeDetachedRuleResult (entity: Entity) (service: RuleValidationService) result =
        lock detachedRuleResultGate (fun () ->
            detachedRuleResults.[entity.filepath] <- struct (entity, service, result)

            match detachedRuleResultNodes.TryGetValue entity.filepath with
            | true, node ->
                detachedRuleResultOrder.Remove node
                detachedRuleResultOrder.AddLast node
            | _ ->
                let node = detachedRuleResultOrder.AddLast entity.filepath
                detachedRuleResultNodes.[entity.filepath] <- node

            while detachedRuleResults.Count > maxDetachedRuleResults do
                removeDetachedRuleResultUnsafe detachedRuleResultOrder.First.Value)

    let validationCancelled () =
        let check = cancellationCheck.Value
        not (isNull (box check)) && check ()

    let runRuleValidation (entity: Entity) =
        match services.ruleValidationService with
        | None -> Some OK
        | Some service ->
            let check = cancellationCheck.Value
            if isNull (box check) then
                Some(service.RuleValidateEntity entity)
            else
                service.RuleValidateEntityCancellable(entity, check)

    let tryTakeDetachedRuleResult (entity: Entity) =
        lock detachedRuleResultGate (fun () ->
            match services.ruleValidationService with
            | Some service ->
                match detachedRuleResults.TryGetValue entity.filepath with
                | true, struct (cachedEntity, cachedService, result) when
                    Object.ReferenceEquals(cachedEntity, entity)
                    && Object.ReferenceEquals(cachedService, service)
                    ->
                    removeDetachedRuleResultUnsafe entity.filepath
                    Some result
                | true, _ ->
                    removeDetachedRuleResultUnsafe entity.filepath
                    None
                | _ -> None
            | None -> None)

    let addToCache (entity: Entity) errors =
        // Try to get all other files which this file had generated errors for
        // And all files that it now generates errors for
        errorCache.AddErrorsGeneratedByFile(entity, errors)
    // let cache = (errorCache :> System.Collections.Generic.IDictionary<_,_>)
    // if cache.ContainsKey entity.filepath then cache.[entity.filepath] <- errors else cache.Add(entity.filepath, errors)
    let getErrorsForEntity (entity: Entity) = errorCache.GetErrorsForEntity entity

    /// Validate the current entities without changing ErrorCache. This is used
    /// after an editor resource has been committed: completion may read the game
    /// concurrently under the same read lock, while diagnostic publication is
    /// guarded by the document/model versions in the language server.
    let validateInteractiveDetached (entities: struct (Entity * Lazy<'T>) list) =
        if not settings.useRules || services.ruleValidationService.IsNone then
            []
        else
            entities
            |> List.collect (fun struct (entity, _) ->
                let fileIndex = fileIndexOfFile entity.filepath

                let result =
                    match runRuleValidation entity with
                    | Some result -> result
                    | None -> raise (OperationCanceledException("Rule validation snapshot was superseded."))

                storeDetachedRuleResult entity services.ruleValidationService.Value result

                result
                |> function
                    | Invalid(_, errors) ->
                        errors
                        |> List.filter (fun error ->
                            error.code <> "CW100"
                            && error.range.FileIndex = fileIndex)
                    | _ -> [])

    /// Drop cached diagnostics generated by the old version of an edited file.
    /// Detached interactive validation intentionally does not repopulate this
    /// cross-file cache; save/deep validation remains its authoritative writer.
    let invalidateInteractive (entities: struct (Entity * Lazy<'T>) list) =
        entities
        |> List.iter (fun struct (entity, _) ->
            removeDetachedRuleResult entity.filepath
            addToCache entity Seq.empty |> ignore)

    /// Validate only the edited entities against CWT rules. This intentionally skips
    /// validators that inspect the full resource set; it is the latency-sensitive path
    /// used while typing; save-time or explicit validation supplies global diagnostics.
    let validateInteractive (entities: struct (Entity * Lazy<'T>) list) =
        if not settings.useRules || services.ruleValidationService.IsNone then
            []
        else
            let impactedFileBag = ConcurrentBag<string>()
            use ruleCancellation = new System.Threading.CancellationTokenSource()

            let cancelledResult () =
                ruleCancellation.Cancel()
                OK

            let ruleValidate (e: Entity) =
                if validationCancelled () then
                    cancelledResult ()
                else
                    let result =
                        match tryTakeDetachedRuleResult e with
                        | Some cached -> Some cached
                        | None -> runRuleValidation e

                    match result with
                    | None -> cancelledResult ()
                    | Some _ when validationCancelled () -> cancelledResult ()
                    | Some res ->
                        let errors =
                            res
                            |> function
                                | Invalid(_, es) -> es
                                | _ -> []

                        let impactedFiles = addToCache e errors
                        impactedFiles |> Seq.iter impactedFileBag.Add
                        let fileIndex = fileIndexOfFile e.filepath

                        res
                        |> function
                            | Invalid(_, es) ->
                                Invalid(Guid.NewGuid(), es |> List.filter (fun error -> error.range.FileIndex = fileIndex))
                            | _ -> OK

            let directErrors =
                entities
                |> List.map (fun struct (e, _) -> e)
                <&!!&> ruleValidate
                |> function
                    | Invalid(_, es) -> es
                    | _ -> []

            // Parallel rule workers communicate cancellation through a shared flag.
            // Raising inside PLINQ would wrap OperationCanceledException and leak it
            // past the cancellable API instead of returning None to the LSP caller.
            if ruleCancellation.IsCancellationRequested || validationCancelled () then
                raise (OperationCanceledException("Rule validation snapshot was superseded."))

            let nonSelfErrors =
                entities
                |> List.choose (fun struct (e, _) -> errorCache.GetNonSelfErrorsForFile e)
                |> List.collect id

            let impactedErrors =
                impactedFileBag
                |> Seq.choose errorCache.GetErrorsForFile
                |> Seq.collect id
                |> List.ofSeq

            directErrors @ nonSelfErrors @ impactedErrors
            |> List.filter (fun error -> error.code <> "CW100")

    let validate (shallow: bool) (entities: struct (Entity * Lazy<'T>) list) =
        log (sprintf "Validating %i files" entities.Length)
        // log $"Validation cache size %i{errorCache.}"
        let oldEntities = EntitySet(resources.AllEntities())
        let newEntities = EntitySet entities

        let runValidators f (validators: (StructureValidator<'T> * string) list) =
            (validators <&!!&> (fun (v, s) -> duration (fun _ -> f v) s)
             |> (function
             | Invalid(_, es) -> es
             | _ -> []))
            @ (if not settings.experimental then
                   []
               else
                   settings.experimentalValidators <&!&> (fun (v, s) -> duration (fun _ -> f v) s)
                   |> (function
                   | Invalid(_, es) -> es
                   | _ -> []))
        // log "Validating misc"
        let res = runValidators (fun f -> f oldEntities newEntities) validators
        // log "Validating rules"
        // let rres = (if settings.useRules && services.ruleValidationService.IsSome then (runValidators (fun f -> f oldEntities newEntities) [services.ruleValidationService.Value.RuleValidate(), "rules"]) else [])
        let rres = validateInteractive entities

        let shallow, deep =
            if settings.debugRulesOnly then
                rres, []
            else

                // log "Validating files"
                let fres =
                    settings.fileValidators
                    <&!&> (fun (v, s) -> duration (fun _ -> v resources newEntities) s)
                    |> (function
                    | Invalid(_, es) -> es
                    | _ -> [])
                // log "Validating effects/triggers"
                let lres =
                    settings.lookupValidators
                    <&!&> (fun (v, s) -> duration (fun _ -> v services.lookup oldEntities newEntities) s)
                    |> function
                        | Invalid(_, es) -> es
                        | _ -> []

                let lfres =
                    settings.lookupFileValidators
                    <&!&> (fun (v, s) ->
                        duration
                            (fun _ ->
                                v
                                    services.fileManager
                                    services.ruleValidationService
                                    services.lookup
                                    resources
                                    newEntities)
                            s)
                    |> function
                        | Invalid(_, es) -> es
                        | _ -> []

                let hres =
                    if settings.experimental && (not shallow) then
                        settings.heavyExperimentalValidators
                        <&!&> (fun (v, s) -> duration (fun _ -> v services.lookup oldEntities newEntities) s)
                        |> function
                            | Invalid(_, es) -> es
                            | _ -> []
                    else
                        []

                res @ fres @ lres @ lfres @ rres, hres

        shallow, deep

    let validateLocalisation (entities: struct (Entity * Lazy<'T>) list) =
        log (sprintf "Localisation check %i files" entities.Length)
        let timer = System.Diagnostics.Stopwatch()
        timer.Start()
        let oldEntities = EntitySet(resources.AllEntities())
        let newEntities = EntitySet entities

        let vs =
            (settings.localisationValidators
             |> List.map (fun v -> v oldEntities (services.localisationKeys ()) newEntities)
             |> List.fold (<&&>) OK)

        let typeVs =
            if settings.useRules && services.infoService.IsSome then
                (entities
                 |> List.map (fun struct (e, _) -> e)
                 |> PSeq.map services.infoService.Value.GetTypeLocalisationErrors)
                |> Seq.fold (<&&>) OK
            else
                OK

        let vs = if settings.debugRulesOnly then typeVs else vs <&&> typeVs
        log (sprintf "Localisation check took %ims" timer.ElapsedMilliseconds)
        // logDiag (sprintf "%A" vs)
        (vs
         |> (function
         | Invalid(_, es) -> es
         | _ -> []))

    let createScopeContextFromReplace (rep: ReplaceScopes option) =
        match rep with
        | None -> noneContext
        | Some rs ->
            let ctx = defaultContext

            let prevctx =
                match rs.prevs with
                | Some prevs -> { ctx with Scopes = prevs }
                | None -> ctx

            let newctx =
                match (rs.this, rs.froms) with
                | Some this, Some froms ->
                    { prevctx with
                        Scopes = this :: prevctx.PopScope
                        From = froms
                        FromDepth = FromPath.FixedSlots
                        FromDepthStack = [] }
                | Some this, None ->
                    { prevctx with
                        Scopes = this :: prevctx.PopScope }
                | None, Some froms ->
                    { prevctx with
                        From = froms
                        FromDepth = FromPath.FixedSlots
                        FromDepthStack = [] }
                | None, None -> prevctx

            match rs.root with
            | Some root -> { newctx with Root = root }
            | None -> newctx

    let globalTypeDefLoc () =
        let valLocCommand = validateLocalisationCommand services.lookup

        let validateLoc (values: struct (string * range) array) (locdef: TypeLocalisation) =
            let res1 (value: string) =
                let validate (locentry: LocEntry) =
                    valLocCommand locentry (createScopeContextFromReplace locdef.replaceScopes)

                services.lookup.proccessedLoc
                |> List.fold
                    (fun r (_, m) ->
                        Map.tryFind value m
                        |> function
                            | Some le -> validate le <&&> r
                            | None -> r)
                    OK
            //     let value = locdef.prefix + value + locdef.suffix
            //     validateLocalisationCommand (createScopeContextFromReplace locdef.replaceScopes) value
            // let validateLocEntry (locentry : LocEntry<_>) =
            // locentry.
            // services.lookup.proccessedLoc |> List.fold (fun state (l, keys)  -> state <&&> (Map.tryFind value keys |> Option.map validateLocEntry |> Option.defaultValue OK ) OK
            values |> Seq.filter (fun struct (s, _) -> s.Contains('.') |> not)
            <&!&> (fun struct (key, range) ->
                let fakeLeaf = LeafValue(Value.Bool true, range)
                let lockey = locdef.prefix + key + locdef.suffix

                if locdef.explicitField.IsNone then res1 lockey else OK
                <&&> checkLocKeysLeafOrNode (services.localisationKeys ()) lockey fakeLeaf)

        let validateType (typename: string) (values: struct (string * range) array) =
            match services.lookup.typeDefs |> List.tryFind (fun td -> td.name = typename) with
            | None -> OK
            | Some td ->
                td.localisation |> List.filter (fun locdef -> locdef.required)
                <&!&> validateLoc values

        let validateSubType (typename: string) (values: struct (string * range) array) =
            let splittype = typename.Split('.', 2)

            if splittype.Length > 1 then
                match services.lookup.typeDefs |> List.tryFind (fun td -> td.name = splittype.[0]) with
                | None -> OK
                | Some td ->
                    match td.subtypes |> List.tryFind (fun st -> st.name = splittype.[1]) with
                    | None -> OK
                    | Some st ->
                        st.localisation |> List.filter (fun locdef -> locdef.required)
                        <&!&> validateLoc values
            else
                OK

        services.lookup.typeDefInfoForValidation |> Map.toList
        <&!&> (fun (t, l) -> validateType t l)
        <&&> (services.lookup.typeDefInfoForValidation |> Map.toList
              <&!&> (fun (t, l) -> validateSubType t l))


    member _.Validate(shallow: bool, entities: struct (Entity * Lazy<'T>) list) = validate shallow entities
    member _.ValidateCancellable(shallow: bool, entities: struct (Entity * Lazy<'T>) list, shouldCancel: unit -> bool) =
        let previous = cancellationCheck.Value
        cancellationCheck.Value <- shouldCancel

        try
            if shouldCancel () then
                None
            else
                try
                    let result = validate shallow entities
                    if shouldCancel () then None else Some result
                with :? OperationCanceledException ->
                    None
        finally
            cancellationCheck.Value <- previous

    member _.ValidateInteractive(entities: struct (Entity * Lazy<'T>) list) = validateInteractive entities
    member _.ValidateInteractiveDetached(entities: struct (Entity * Lazy<'T>) list) =
        validateInteractiveDetached entities
    member _.ValidateInteractiveDetachedCancellable(entities: struct (Entity * Lazy<'T>) list, shouldCancel: unit -> bool) =
        let previous = cancellationCheck.Value
        cancellationCheck.Value <- shouldCancel

        try
            if shouldCancel () then
                None
            else
                try
                    let result = validateInteractiveDetached entities
                    if shouldCancel () then None else Some result
                with :? OperationCanceledException ->
                    None
        finally
            cancellationCheck.Value <- previous

    member _.InvalidateInteractive(entities: struct (Entity * Lazy<'T>) list) =
        invalidateInteractive entities
    member _.ValidateLocalisation(entities: struct (Entity * Lazy<'T>) list) = validateLocalisation entities
    member _.ValidateGlobalLocalisation() = globalTypeDefLoc ()

    /// 清理不存在文件的缓存条目，防止内存泄漏
    member _.Cleanup(existingFiles: Set<string>) =
        errorCache.Cleanup existingFiles
        lock detachedRuleResultGate (fun () ->
            for filePath in detachedRuleResults.Keys |> Seq.toArray do
                if not (existingFiles.Contains filePath) then
                    removeDetachedRuleResultUnsafe filePath)

    member _.InvalidateFile(filepath: string) =
        removeDetachedRuleResult filepath

    member _.CachedRuleErrors(entities: struct (Entity * Lazy<'T>) list) =
        let res =
            entities
            |> List.map (fun struct (e, l) -> (struct (e, l)), errorCache.GetErrorsForEntity e)

        let forced =
            res
            |> List.filter (fun (e, errors) -> errors.IsNone)
            |> List.choose (fun (struct (e, _), _) -> errorCache.GetErrorsForEntity e)
            |> List.collect id

        (res |> List.choose (fun (_, errors) -> errors) |> List.collect id) @ forced

    member _.ErrorCache() = errorCache
