[package]
name = "cwtools-semantic"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
cwtools-process = { path = "../cwtools-process" }
cwtools-script-syntax = { path = "../cwtools-script-syntax" }
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
rusqlite.workspace = true

[lints]
workspace = true
